name: Build and Release MapChooser

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build DLL
        run: dotnet publish -c Release -o ./publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            publish/MapChooser.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
